#!/bin/bash
#Declare Version
T_VERSION='1.8.5'
#Download Terraform Latest Zip File
echo "We are Downloading Terraform Version: ${T_VERSION).."
wget https://releases.hashicorp.com/terraform/${T_VERSION}/terraform S
echo "Unzipping Terraform File and Removing Zip File.."
unzip terraform.zip && rm -rf terraform.zip
echo "Removing Existing Terraform File if exists.."
rm -rf /usr/local/bin/terraform
chmod 700 terraform
echo "Moving Terraform File to /usr/local/bin/.."
mv terraform /usr/local/bin/
echo "Checking Terraform Version.."
terraform --version
